name: "Verify C# formatting"

on:
  push:
    paths:
      - "languages/csharp/exercise/**/*.cs"
  pull_request:
    paths:
      - "languages/csharp/exercise/**/*.cs"

jobs:
  verify-csharp-for-repository:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
